name: Django Docker CI/CD 

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: checkout code 
      uses: actions/checkout@4 
    
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        cd myproject
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    
    - name: Run Django test
      run: |
        python manage.py test
    
    - name: Build Docker image 
      run:docker build -t my-django-app .

    - name: Test Docker image
      run: |
        docker run --rm my-django-app python manage.py check 
    
    - name: Login to Docker Hub 
      uses: docker/login-acion@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Docker Hub 
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: kinglm/my-django-app:latest